import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/Components/Navbar/Navbar'

import Link from 'next/link'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Indexlost',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Paste the <link> tag for your Google Font here */}
        <Link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap"
        />
      </Head>
      <body >
        <Navbar></Navbar>

        <div className='   mt-[86px]'>
          <div className=' '>
            {children}
          </div>
        </div>

      </body>
    </html>
  )
}
